version: "3.9"
volumes:
  godot-ps2-volume:
services:
  compiler:
    environment:
      TERM: xterm-256color
    network_mode: host
    image: "godot-ps2"
    tty: true
    container_name: godot-ps2-compiler
    volumes:
      - godot-ps2-volume:/godot
      - ./:/host
      - ./godot:/godot
